---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: kafka
      version: 4.11.1
      sourceRef:
        kind: HelmRepository
        name: kafka
      interval: 10m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kafka
  namespace: infrastructure
spec:
  interval: 60m
  url: https://strimzi.io/charts/
