---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-ui-production
  namespace: kafka-production
spec:
  interval: 60m
  releaseName: kafka-ui-production
  chart:
    spec:
      chart: akhq/akhq
      version: 0.25.1
      sourceRef:
        kind: HelmRepository
        name: akhq
      interval: 10m
  values:
    configuration:
      akhq:
        connections:
          kafka-production-cluster:
            properties:
              bootstrap.servers: "kafka-production-cluster-kafka-bootstrap:9092"    
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: akhq
  namespace: kafka-production
spec:
  interval: 60m
  url: https://akhq.io/