---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kafka-failover
spec:
  interval: 60m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 10m
  values:
    controller:
      containerSecurityContext:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
      # resources:
      #   limits:
      #     cpu: 1000m
      #     memory: 650Mi
      #   requests:
      #     cpu: 100m
      #     memory: 650Mi
      config:
        ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA"
        ssl-protocols: "TLSv1.2 TLSv1.3"
      admissionWebhooks:
        # patchWebhookJob:
        #   resources:
        #     limits:
        #       cpu: 1000m
        #       memory: 650Mi
        #     requests:
        #       cpu: 100m
        #       memory: 650Mi
        # createSecretJob:
        #   resources:
        #     limits:
        #       cpu: 1000m
        #       memory: 650Mi
        #     requests:
        #       cpu: 100m
        #       memory: 650Mi
        patch:
          podAnnotations:
            linkerd.io/inject: disabled
      service:
        externalTrafficPolicy: Local
      replicaCount: 1
      podAnnotations:
        config.linkerd.io/skip-inbound-ports: 80,443
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
    defaultBackend:
      enabled: true
      replicaCount: 1
      resources:
        limits:
          cpu: 1000m
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 50Mi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: kafka-failover
spec:
  interval: 60m
  url: https://kubernetes.github.io/ingress-nginx