---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka-cluster-operator-failover
  namespace: kafka-failover
spec:
  interval: 60m
  releaseName: kafka-cluster-operator-failover
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.45.0
      sourceRef:
        kind: HelmRepository
        name: kafka
      interval: 10m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kafka
  namespace: kafka-failover
spec:
  interval: 60m
  url: https://strimzi.io/charts/

